---
- hosts: elam
  tasks:
    - name: Stop the HTTP server
      service:
        name: apache2
        state: stopped
      ignore_errors: yes  # Ignore errors if the service is not running

    - name: Uninstall the HTTP server
      apt:
        name: apache2
        state: absent
