---
- hosts: elam
  tasks:
    - name: Install an HTTP server (Apache)
      apt:
        name: apache2
        state: present

    - name: Start an HTTP server (Apache)
      service:
        name: apache2
        state: started

    - name: Copy an HTML file
      copy:
        src: /root/ansible/index.html
        dest: /var/www/html
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: apache2
        state: restarted

